### ISSUE TITLE
好像现在不能用了？

### ISSUE THREAD

**Issue by yangxuan8282** [qwIvan/libiplayer#1]
之前试过当时记得部分磁力链接能放的，今天再试发现用不了了，试了几个练级都不行

**Comment by qwIvan** [comment]
现在没接口

**Comment by yangxuan8282** [comment]
回复好快，看你在 v2ex 上回帖说原理是边下边播，那 aria2 + 本地播放器是不是也可以实现这样的效果，只不过播放完要自己清理文件
